# Generated by Django 4.2.1 on 2023-08-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_group', models.CharField(max_length=250, null=True)),
                ('position', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Child_Group',
                'verbose_name_plural': 'Child_Groups',
            },
        ),
        migrations.CreateModel(
            name='IdentityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_group', models.CharField(max_length=256, null=True)),
                ('abb', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Identity_Group',
                'verbose_name_plural': 'Identity_Groups',
            },
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_group', models.CharField(max_length=250)),
                ('parent_id', models.IntegerField(default=0)),
                ('abb', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Material_Group',
                'verbose_name_plural': 'Material_Groups',
            },
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_abb', models.CharField(max_length=256, null=True)),
                ('child_desc', models.CharField(max_length=256, null=True)),
                ('value', models.CharField(max_length=256, null=True)),
                ('child_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coding.child')),
                ('identity_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.identitygroup')),
                ('material_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.materialgroup')),
            ],
        ),
        migrations.AddField(
            model_name='identitygroup',
            name='material_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.materialgroup'),
        ),
        migrations.AddField(
            model_name='child',
            name='identity_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.identitygroup'),
        ),
        migrations.AddField(
            model_name='child',
            name='material_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.materialgroup'),
        ),
    ]
