# Generated by Django 4.2.1 on 2023-08-17 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_group', models.CharField(max_length=250)),
                ('material_parent_id', models.IntegerField(default=0)),
                ('material_abb', models.CharField(max_length=250, null=True)),
                ('is_parent', models.BooleanField(default=False)),
                ('parent_child_id', models.IntegerField(default=0)),
                ('identity_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coding.materialgroup')),
            ],
            options={
                'verbose_name': 'Material_Group',
                'verbose_name_plural': 'Material_Groups',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_group', models.CharField(max_length=256, null=True)),
                ('child_position', models.IntegerField(default=0)),
                ('child_parent_id', models.IntegerField(default=0)),
                ('child_desc', models.IntegerField(default=0)),
                ('child_abb', models.ManyToManyField(to='Coding.child')),
                ('material_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.materialgroup')),
            ],
            options={
                'verbose_name': 'Child_Group',
                'verbose_name_plural': 'Child_Groups',
            },
        ),
    ]
