# Generated by Django 4.2.1 on 2023-08-17 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_group', models.CharField(max_length=256, null=True)),
                ('child_position', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Child_Group',
                'verbose_name_plural': 'Child_Groups',
            },
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_group', models.CharField(max_length=250)),
                ('material_parent_id', models.IntegerField(default=0)),
                ('material_abb', models.CharField(max_length=250, null=True)),
                ('identity_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.materialgroup')),
            ],
            options={
                'verbose_name': 'Material_Group',
                'verbose_name_plural': 'Material_Groups',
            },
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_abb', models.CharField(max_length=256, null=True)),
                ('value_desc', models.CharField(max_length=256, null=True)),
                ('child_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_group_related', to='Coding.child')),
                ('material_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.materialgroup')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='child_parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_parent_id', to='Coding.materialgroup'),
        ),
        migrations.AddField(
            model_name='child',
            name='material_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.materialgroup'),
        ),
    ]
