# Generated by Django 4.2.1 on 2023-08-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialgroup',
            name='identity_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coding.materialgroup'),
        ),
    ]
