# Generated by Django 4.2.1 on 2023-08-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='child_abb',
        ),
        migrations.RemoveField(
            model_name='child',
            name='child_desc',
        ),
        migrations.AddField(
            model_name='child',
            name='child_abb',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='child_desc',
            field=models.ManyToManyField(null=True, to='Coding.child'),
        ),
    ]
