# Generated by Django 4.2.1 on 2023-08-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_id_as_parent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='child_id_as_child',
            field=models.IntegerField(null=True),
        ),
    ]
