# Generated by Django 4.2.1 on 2023-08-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0002_remove_child_child_abb_remove_child_child_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='child_desc',
        ),
        migrations.AddField(
            model_name='child',
            name='child_desc',
            field=models.JSONField(null=True),
        ),
    ]
