# Generated by Django 4.2.1 on 2023-08-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0003_alter_child_child_parent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialgroup',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
