# Generated by Django 4.2.1 on 2023-08-17 16:32

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0003_remove_child_child_desc_child_child_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_desc',
            field=django_jsonform.models.fields.JSONField(null=True),
        ),
    ]
