# Generated by Django 4.2.1 on 2023-08-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0003_alter_values_child_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='child_id_as_child',
        ),
        migrations.AddField(
            model_name='values',
            name='child_id_as_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coding.child'),
        ),
    ]
