# Generated by Django 4.2.1 on 2023-08-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0004_remove_values_child_id_as_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
