# Generated by Django 4.2.1 on 2023-08-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0004_materialgroup_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialgroup',
            name='identity_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_reference_name', to='Coding.materialgroup'),
        ),
    ]
