# Generated by Django 4.2.1 on 2023-08-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0004_alter_child_child_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='child_abb',
        ),
    ]
