# Generated by Django 4.2.1 on 2023-08-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0005_alter_values_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_id_as_parent',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='values',
            name='value',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
