# Generated by Django 4.2.1 on 2023-08-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0006_alter_child_child_id_as_parent_alter_values_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='value_child_relation',
            field=models.ManyToManyField(null=True, to='Coding.child'),
        ),
        migrations.AlterField(
            model_name='values',
            name='child_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_group_related', to='Coding.child'),
        ),
        migrations.AlterField(
            model_name='values',
            name='child_id_as_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_parent_id_related', to='Coding.child'),
        ),
    ]
