# Generated by Django 4.2.1 on 2023-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0007_alter_materialgroup_identity_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_value_id',
            field=models.IntegerField(default=0),
        ),
    ]
