# Generated by Django 4.2.1 on 2023-08-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0007_values_value_child_relation_alter_values_child_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='value_child_relation',
        ),
    ]
