# Generated by Django 4.2.1 on 2023-08-14 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0008_remove_values_value_child_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='one_to_one',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_to_child_one', to='Coding.child'),
        ),
    ]
