# Generated by Django 4.2.1 on 2023-08-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0008_child_child_value_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialgroup',
            name='parent_child_id',
            field=models.IntegerField(default=0),
        ),
    ]
