# Generated by Django 4.2.1 on 2023-08-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0009_values_one_to_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='one_to_one',
        ),
        migrations.CreateModel(
            name='SP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp', models.CharField(max_length=256, null=True)),
                ('child_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coding.child')),
                ('identity_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.identitygroup')),
                ('material_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coding.materialgroup')),
                ('value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coding.values')),
            ],
        ),
    ]
