# Generated by Django 4.2.1 on 2023-08-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0010_remove_values_one_to_one_sp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp',
            name='value',
        ),
    ]
