# Generated by Django 4.2.1 on 2023-08-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0011_remove_sp_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coding.values'),
        ),
    ]
