# Generated by Django 4.2.1 on 2023-08-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0012_sp_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='child_id_as_parent',
        ),
        migrations.AddField(
            model_name='child',
            name='child_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='child_id_as_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_child_id_related', to='Coding.child'),
        ),
        migrations.AddField(
            model_name='values',
            name='parent_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
