# Generated by Django 4.2.1 on 2023-08-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0013_remove_values_child_id_as_parent_child_child_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='parent_name',
        ),
    ]
