# Generated by Django 4.2.1 on 2023-08-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0014_remove_values_parent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='child_name',
        ),
    ]
