# Generated by Django 4.2.1 on 2023-08-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coding', '0015_remove_child_child_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='child_id_as_child',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
