# Generated by Django 4.2.1 on 2023-07-06 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text_note', models.CharField(max_length=500)),
                ('color_note', models.CharField(max_length=500, null=True)),
                ('create_date', models.DateTimeField(default=datetime.date.today, verbose_name='create date')),
                ('dead_line', models.DateTimeField(null=True, verbose_name='Deadline')),
            ],
        ),
    ]
