# Generated by Django 4.2.1 on 2023-07-06 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stickynotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='create date'),
        ),
    ]
