# Generated by Django 4.2.1 on 2023-06-05 15:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formletters',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000, verbose_name='عنوان نامه'),
        ),
    ]
