# Generated by Django 4.2.1 on 2023-06-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headquarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام ستاد')),
            ],
            options={
                'verbose_name': 'نام ستاد',
                'verbose_name_plural': 'نام ستاد ها',
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام صف')),
            ],
            options={
                'verbose_name': 'صف',
                'verbose_name_plural': 'صف ها',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_name', models.CharField(max_length=35, verbose_name='نام مدیریت')),
                ('code', models.CharField(max_length=10, verbose_name='کد مدیریت')),
                ('english_name', models.CharField(max_length=35, verbose_name='نام انگلیسی مدیریت')),
                ('order', models.IntegerField(max_length=35, verbose_name='ترتیب')),
                ('manager_status', models.CharField(blank=True, choices=[('فعال', 'فعال'), ('غیر فعال', 'غیر فعال')], max_length=15, null=True, verbose_name='وضعیت حضور و غیاب')),
                ('headquarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headquarter', to='HR.headquarter', verbose_name='ستاد')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue', to='HR.queue', verbose_name='صف')),
            ],
            options={
                'verbose_name': 'مدیریت',
                'verbose_name_plural': 'مدیران',
            },
        ),
    ]
