# Generated by Django 4.2.1 on 2023-06-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/HR/Company'),
        ),
    ]
