# Generated by Django 4.2.1 on 2023-06-05 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='نام شرکت')),
                ('code', models.CharField(max_length=10, verbose_name='کد شرکت')),
                ('english_title', models.CharField(max_length=35, verbose_name='نام انگلیسی شرکت')),
                ('company_status', models.CharField(blank=True, choices=[('فعال', 'فعال'), ('غیر فعال', 'غیر فعال')], max_length=15, null=True, verbose_name='وضعیت شرکت')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='نام معاونت')),
                ('code', models.CharField(max_length=10, verbose_name='کد معاونت')),
                ('english_title', models.CharField(max_length=35, verbose_name='نام انگلیسی معاونت')),
                ('department_status', models.CharField(blank=True, choices=[('فعال', 'فعال'), ('غیر فعال', 'غیر فعال')], max_length=15, null=True, verbose_name='وضعیت معاونت')),
                ('department_type', models.CharField(blank=True, choices=[('صف', 'صف'), ('ستاد', 'ستاد')], max_length=15, null=True, verbose_name='نوع معاونت')),
                ('order', models.IntegerField(max_length=35, verbose_name='ترتیب معاونت')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.company')),
            ],
            options={
                'verbose_name': 'معاونت',
                'verbose_name_plural': 'معاونت ها',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='نام دسته سمت')),
                ('code', models.CharField(max_length=10, verbose_name='کد دسته سمت')),
                ('english_title', models.CharField(max_length=35, verbose_name='نام انگلیسی دسته سمت')),
                ('position_status', models.CharField(blank=True, choices=[('فعال', 'فعال'), ('غیر فعال', 'غیر فعال')], max_length=15, null=True, verbose_name='وضعیت دسته سمت')),
                ('grade', models.IntegerField(max_length=35, verbose_name='ترتیب دسته سمت')),
            ],
            options={
                'verbose_name': 'دسته سمت',
                'verbose_name_plural': 'دسته های سمت',
            },
        ),
        migrations.CreateModel(
            name='OU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='نام واحد سازمانی')),
                ('code', models.CharField(max_length=10, verbose_name='کد واحد سازمانی')),
                ('english_title', models.CharField(max_length=35, verbose_name='نام انگلیسی واحد سازمانی')),
                ('ou_status', models.CharField(blank=True, choices=[('فعال', 'فعال'), ('غیر فعال', 'غیر فعال')], max_length=15, null=True, verbose_name='وضعیت واحد سازمانی')),
                ('order', models.IntegerField(max_length=35, verbose_name='ترتیب واخد سازمانی')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.department')),
            ],
            options={
                'verbose_name': 'واحد سازمانی',
                'verbose_name_plural': 'واحد های سازمانی',
            },
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_status',
            field=models.CharField(blank=True, choices=[('فعال', 'فعال'), ('غیر فعال', 'غیر فعال')], max_length=15, null=True, verbose_name='وضعیت مدیر'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='نام سمت')),
                ('code', models.CharField(max_length=10, verbose_name='کد سمت')),
                ('serial', models.CharField(max_length=10, verbose_name='سریال سمت')),
                ('english_title', models.CharField(max_length=35, verbose_name='نام انگلیسی سمت')),
                ('position_status', models.CharField(blank=True, choices=[('فعال', 'فعال'), ('غیر فعال', 'غیر فعال')], max_length=15, null=True, verbose_name='وضعیت سمت')),
                ('position_type', models.CharField(blank=True, choices=[('ساختاری', 'ساختاری'), ('غیر ساختاری', 'غیر ساختاری')], max_length=15, null=True, verbose_name='نوع سمت')),
                ('order', models.IntegerField(max_length=35, verbose_name='ترتیب سمت')),
                ('deputy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.department')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.level')),
                ('ou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.ou')),
                ('report_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.position')),
            ],
            options={
                'verbose_name': 'سمت',
                'verbose_name_plural': 'سمت ها',
            },
        ),
    ]
