# Generated by Django 4.2.1 on 2023-06-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_alter_company_company_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='files',
        ),
        migrations.AddField(
            model_name='company',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_status',
            field=models.CharField(blank=True, choices=[('فعال', 'فعال'), ('غیر فعال', 'غیر فعال')], max_length=15, null=True, verbose_name='وضعیت شرکت'),
        ),
    ]
