# Generated by Django 4.2.1 on 2023-06-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_remove_company_files_company_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='file',
        ),
    ]
