# Generated by Django 4.2.1 on 2023-06-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_remove_company_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
