# Generated by Django 4.2.1 on 2023-06-07 11:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_alter_company_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
