# Generated by Django 4.2.1 on 2023-06-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='headquarter',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='queue',
        ),
        migrations.DeleteModel(
            name='Headquarter',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
