# Generated by Django 4.2.1 on 2023-08-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklinks',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
