# Generated by Django 4.2.1 on 2023-08-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_quicklinks_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'اپ فرعی',
                'verbose_name_plural': 'اپ های فرعی',
            },
        ),
    ]
