# Generated by Django 4.2.1 on 2023-08-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_submenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='slug',
        ),
        migrations.AddField(
            model_name='submenu',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
