# Generated by Django 4.2.1 on 2023-06-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditentry',
            options={'ordering': ['-time'], 'verbose_name': 'لاگ ورود به سیستم', 'verbose_name_plural': 'لاگ های ورود به سیستم'},
        ),
    ]
