# Generated by Django 4.2.1 on 2023-06-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_auditentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditentry',
            options={'verbose_name': 'لاگ ورود به سیستم', 'verbose_name_plural': 'لاگ های ورود به سیستم'},
        ),
    ]
