# Generated by Django 4.2.1 on 2023-08-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('adanger', 'اولویت زیاد؟'), ('bwarning', 'اولویت متوسط؟'), ('csuccess', 'اولویت کم؟')], default='adanger', max_length=30),
        ),
    ]
