# Generated by Django 4.2.1 on 2023-06-04 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='تیتر پیام')),
                ('description', models.CharField(max_length=10, verbose_name='متن پیام')),
                ('notif_status', models.CharField(blank=True, choices=[('خوانده شده', 'خوانده شده'), ('خوانده نشده', 'خوانده نشده')], max_length=15, null=True, verbose_name='وضعیت پیام')),
                ('notifications_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
