# Generated by Django 4.2.1 on 2023-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifications_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان پیام'),
        ),
    ]
