# Generated by Django 4.2.1 on 2023-08-12 11:16

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Codings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildSpecsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_specs_value', models.CharField(default='', max_length=250)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Codings.recipename')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='child_specs_value',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='recipename', chained_model_field='recipename', null=True, on_delete=django.db.models.deletion.CASCADE, to='Codings.childspecsvalue'),
        ),
    ]
