# Generated by Django 4.2.1 on 2023-08-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Codings', '0002_childspecsvalue_recipe_child_specs_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='childspecsvalue',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Codings.subcategory'),
        ),
    ]
