# Generated by Django 4.2.1 on 2023-08-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Codings', '0003_childspecsvalue_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childspecsvalue',
            name='value',
        ),
        migrations.AddField(
            model_name='childspecsvalue',
            name='recipename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Codings.recipename'),
        ),
    ]
