# Generated by Django 4.2.1 on 2023-08-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Codings', '0004_remove_childspecsvalue_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Materia Group', 'verbose_name_plural': 'Material Groups'},
        ),
        migrations.AlterModelOptions(
            name='recipename',
            options={'verbose_name': 'Child Spec', 'verbose_name_plural': 'Child Specs'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Identity Group', 'verbose_name_plural': 'Identity Groups'},
        ),
    ]
