# Generated by Django 4.2.1 on 2023-08-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Codings', '0005_alter_category_options_alter_recipename_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Chain', 'verbose_name_plural': 'Chains'},
        ),
    ]
